[package]
name = "otterc_symbol"
version = "0.1.0"
edition = "2024"

[dependencies]
otterc_ident.path = "../otterc_ident"
otterc_ty.path = "../otterc_ty"

abi_stable.workspace = true
ahash.workspace = true
once_cell.workspace = true
parking_lot.workspace = true
thiserror.workspace = true

[dev-dependencies]
pretty_assertions.workspace = true

[lints]
workspace = true
